name: Add instance to uptimerobot

on:
  issues:
    types: [opened]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@v6
        id: my-script
        with:
          script: |
            var request = require("request");
            var options = { method: 'POST',
              url: 'https://api.uptimerobot.com/v2/newMonitor',
              headers:
              { 'content-type': 'application/x-www-form-urlencoded',
                'cache-control': 'no-cache' },
              form:
              { api_key: '${{ secrets.UPTIMEROBOT_API_KEY }}',
                format: 'json',
                type: '1',
                url: 'http://myMonitorURL.com',
                friendly_name: 'My Monitor' } };
                      
            request(options, function (error, response, body) {
              if (error) throw new Error(error);
                      
              console.log(body);
            });