name: Add instance to uptimerobot

on:
  issues:
    types: [opened, reopened]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install request linkifyjs
      - uses: actions/github-script@v6
        with:
          script: |
            const issueTitleParseUrl = linkify.find(context.issue.title);
            if (issueTitleParseUrl[0]) {
              const instanceHostname = (new URL(issueTitleParseUrl[0].href).hostname;
              console.log(instanceHostname)
              let request = require("request");
              let options = { method: 'POST',
                url: 'https://api.uptimerobot.com/v2/newMonitor',
                headers:
                { 'content-type': 'application/x-www-form-urlencoded',
                  'cache-control': 'no-cache' },
                form:
                { api_key: '${{ secrets.UPTIMEROBOT_API_KEY }}',
                  format: 'json',
                  type: '1',
                  url: 'http://myMonitorURL.com',
                  friendly_name: 'My Monitor' } };
                        
              request(options, function (error, response, body) {
                if (error) throw new Error(error);
                        
                console.log(body);
              });

              console.log(context);
            }
            else {
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `Domain not detected in the title, please edit the title by correcting it like this and reopen the issue:

                Issue title example: [New instance] https://myinstance.com
                `
              })
              github.rest.issues.update({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                state: 'closed'
              })
            }